name: marcci
description: M-Vet App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+19
environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #  flutx:
  #    path: ../flutx14
  connectivity_plus: ^3.0.2
  dio: ^5.1.2

  # Base Dependencies
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.3.0
  flutter_form_builder:
  form_builder_validators: ^8.3.0
  url_launcher: ^6.1.9
  geolocator: ^9.0.2
  image_picker: ^0.8.6+1
  shimmer: ^2.0.0
  intl: ^0.17.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  flutx: ^0.2.0-rc.2

  get: ^4.6.5
  sqflite: ^2.2.4+1
  shared_preferences: ^2.0.17
  google_fonts: ^5.1.0
  fluttertoast: ^8.2.4
  flutter_html: ^3.0.0-beta.2
  material_design_icons_flutter: ^7.0.7296
  form_builder_image_picker: 
  form_builder_phone_field: 
  blurrycontainer: ^1.0.2
  flutter_typeahead: ^5.0.1
  dropdown_search: ^5.0.6
  loading_animations: ^2.2.0
  otp_text_field: ^1.1.3
  flutter_clean_calendar: ^1.1.0
  table_calendar: ^3.0.9
  flutter_countdown_timer: ^4.1.0
  intl_phone_number_input: ^0.7.4
  intl_phone_field: ^3.2.0
  flutter_local_notifications: ^17.0.1
  autocomplete_textfield: ^2.0.1
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  glassmorphism_ui: ^0.3.0
  permission_handler: ^11.3.1
  loading_overlay: ^0.3.0
  modal_progress_hud_nsn: ^0.5.1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.2
  change_app_package_name: ^1.0.0





  # Icons
  flutter_feather_icons: ^2.0.0+1
  flutter_lints: ^2.0.1

dependency_overrides:
  intl: any
  http: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/data/
